Repository data-fair/data-fair, pull requests merged in 2025-04, with the labels that each got.

#240 fix: missing const properties in app config dataset definitions
  api/src/applications/utils.js
  api/src/base-applications/router.js
  test/applications.js
  test/base-applications.js
  test/setup-teardown.js
Labels: fix

#241 fix: some broken cases of transform expressions
  api/src/datasets/utils/data-streams.js
  api/src/datasets/utils/rest.js
  test/transform.js
Labels: fix

#239 chore: enhance doc
  api/contract/api-docs.js
  api/contract/application-api-docs.js
  api/contract/dataset-private-api-docs.js
  api/contract/site-catalog-api-docs.js
  api/types/app-config/schema.js
Labels: ignore-for-release

#242 fix: handle potential null reference in catalog when listing dataset resources
  ui/public/components/catalog/catalog-datasets.vue
Labels: fix

#245 feat: support overwriting keys of properties from extensions
  api/contract/dataset.js
  api/src/app.js
  api/src/datasets/es/manage-indices.js
  api/src/datasets/router.js
  api/src/datasets/utils/extensions.js
  api/src/datasets/utils/patch.js
  api/src/datasets/utils/rest.js
  api/src/workers/index.js
  package-lock.json
  package.json
  test/master-data.js
  ui/public/components/dataset/dataset-add-property-dialog.vue
  ui/public/components/dataset/dataset-extensions.vue
Labels: feature
