Repository data-fair/data-fair, pull requests merged in 2025-03, with the labels that each got.

#229 feat: transform data from files datasets
  api/contract/dataset.js
  api/contract/master-data.js
  api/src/app.js
  api/src/datasets/es/index-stream.js
  api/src/datasets/utils/data-streams.js
  api/src/datasets/utils/extensions.js
  api/src/datasets/utils/fields-sniffer.js
  api/src/datasets/utils/files.ts
  api/src/datasets/utils/geo.js
  api/src/datasets/utils/index.js
  api/src/datasets/utils/patch.js
  api/src/datasets/utils/rest.js
  api/src/datasets/utils/schema.js
  api/src/misc/utils/thumbnails.js
  api/src/workers/file-downloader.js
  api/src/workers/file-normalizer.js
  api/src/workers/rest-exporter-csv.js
  shared/expr-eval.js
  test/datasets.js
  test/expr-eval.js
  test/file-validation.js
  test/geo-files.js
  test/resources/datasets/dataset1-invalid.csv
  test/transform.js
  test/virtual-datasets.js
  ui/public/components/dataset/dataset-expr-eval-doc.vue
  ui/public/components/dataset/dataset-extension-expr-eval-preview.vue
  ui/public/components/dataset/dataset-properties-slide.vue
  ui/public/components/dataset/dataset-property-capabilities.vue
  ui/public/components/dataset/dataset-property-labels.vue
  ui/public/components/dataset/dataset-property-transform.vue
  ui/public/components/dataset/dataset-property-validation.vue
  upgrade/4.34.0/x-transform-type.ts
Labels: feature

#230 feat: handle superficial names changes in updated files
  api/src/datasets/utils/data-streams.js
  test/datasets-drafts.js
  test/resources/datasets/dataset1-names.csv
Labels: feature

#232 chore: update api-docs
  api/contract/api-docs.js
  api/contract/application-api-docs.js
  api/contract/catalog-api-docs.js
  api/contract/dataset-api-docs.js
  api/contract/dataset-private-api-docs.js
  api/contract/journal.js
  api/contract/master-data.js
  api/contract/remote-service-api-docs.js
  api/contract/site-catalog-api-docs.js
  api/contract/status.js
  api/contract/utils.js
  api/src/misc/utils/permissions.js
  docker-compose.yml
  ui/public/components/application/application-actions.vue
  ui/public/components/dataset/dataset-actions.vue
  ui/public/components/open-api.vue
  ui/public/components/remote-service/remote-service-actions.vue
  ui/public/pages/api-doc.vue
  ui/public/pages/application/_id/api-doc.vue
  ui/public/pages/dataset/_id/api-doc.vue
  ui/public/pages/dataset/_id/description.vue
  ui/public/pages/dataset/_id/index.vue
  ui/public/pages/remote-service/_id/api-doc.vue
  ui/public/pages/remote-service/_id/description.vue
  ui/public/pages/remote-service/_id/index.vue
Labels: ignore-for-release

#233 feat: compatibility layer for other vendor records API
  .gitignore
  api/config/custom-environment-variables.cjs
  api/config/default.cjs
  api/config/development.cjs
  api/config/test.cjs
  api/contract/dataset-api-docs.js
  api/contract/dataset-private-api-docs.js
  api/contract/settings.js
  api/src/app.js
  api/src/catalogs/plugins/ods/api-compat.ts
  api/src/catalogs/plugins/ods/lexic.pegjs
  api/src/catalogs/plugins/ods/where.peg.d.ts
  api/src/catalogs/plugins/ods/where.peg.js
  api/src/catalogs/plugins/ods/where.pegjs
  api/src/datasets/es/commons.js
  api/src/datasets/router.js
  api/src/datasets/utils/flatten.ts
  api/src/misc/utils/api-docs.js
  api/src/remote-services/utils.js
  eslint.config.mjs
  package-lock.json
  package.json
  test/compat-ods.js
  ui/nuxt.config.js
  ui/public/pages/settings.vue
Labels: feature

#235 chore: add an env var to use openapi-viewer V2
  api/config/custom-environment-variables.cjs
  api/config/default.cjs
  api/config/development.cjs
  ui/nuxt.config.js
  ui/public/components/open-api.vue
  ui/public/pages/api-doc.vue
  ui/public/pages/application/_id/api-doc.vue
  ui/public/pages/dataset/_id/api-doc.vue
  ui/public/pages/remote-service/_id/api-doc.vue
Labels: ignore-for-release

#236 feat: add summaries to api docs
  api/config/development.cjs
  api/contract/api-docs.js
  api/contract/application-api-docs.js
  api/contract/catalog-api-docs.js
  api/contract/dataset-api-docs.js
  api/contract/dataset-private-api-docs.js
  api/contract/master-data.js
  api/contract/remote-service-api-docs.js
  api/contract/site-catalog-api-docs.js
  api/src/misc/utils/permissions.js
Labels: feature

#237 fix: upgrade polygon repair tools and fix some problems with multi-polygons
  Dockerfile
  api/src/datasets/utils/geo.js
  test/geo-files.js
  test/resources/geo/kinked-multipolygons.geojson
Labels: fix
